server:
  port: 10003

spring:
  application:
    name: chat-demo
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max

  data:
    redis:
      host: 127.0.0.1
      password: 123456
      port: 6379